"""WIN5 domain package."""

from .enums import (
    Win5JudgementOutcome,
    Win5RoundSourceKind,
    Win5RoundStatus,
    Win5RoundType,
    Win5SeasonStatus,
    Win5SubmissionStatus,
    Win5SubmissionTier,
)
from .errors import (
    Win5DomainError,
    Win5RaceInvariantError,
    Win5ResultInvariantError,
    Win5SubmissionInvariantError,
)
from .invariants import (
    MIN_NORMAL_WIN5_RACE_ENTRIES,
    validate_accepted_submission_uniqueness_per_persona_round,
    validate_normal_round_result_structure,
    validate_normal_round_submission_structure,
    validate_pick_race_membership,
    validate_special_round_result_structure,
    validate_special_round_submission_structure,
    validate_submission_for_round,
    validate_win5_round_open_readiness,
    validate_win5_round_race_cardinality,
)
from .models import (
    Win5Placement,
    Win5Race,
    Win5RaceEntry,
    Win5RaceResult,
    Win5Round,
    Win5Submission,
    Win5SubmissionPick,
)
from .scoring import (
    WIN5_NORMAL_REWARD_POLICY_VERSION,
    WIN5_NORMAL_SCORING_POLICY_VERSION,
    Win5NormalJudgementItem,
    Win5NormalResultPlacement,
    Win5NormalScoringPick,
    Win5NormalSubmissionScore,
    fingerprint_normal_result,
    normal_tier_capacity,
    score_normal_submission,
    validate_normal_score_totals,
)
from .special_results import Win5SpecialResultWinner, fingerprint_special_result
from .special_scoring import (
    WIN5_SPECIAL_REWARD_POLICY_VERSION,
    WIN5_SPECIAL_SCORING_POLICY_VERSION,
    WIN5_SPECIAL_VOID_SCORING_POLICY_VERSION,
    Win5SpecialJudgementItem,
    Win5SpecialScoringPick,
    Win5SpecialSubmissionScore,
    score_special_submission,
    validate_special_score_totals,
)
from .special_voids import fingerprint_special_void_state

__all__ = [
    "MIN_NORMAL_WIN5_RACE_ENTRIES",
    "WIN5_NORMAL_REWARD_POLICY_VERSION",
    "WIN5_NORMAL_SCORING_POLICY_VERSION",
    "WIN5_SPECIAL_REWARD_POLICY_VERSION",
    "WIN5_SPECIAL_SCORING_POLICY_VERSION",
    "WIN5_SPECIAL_VOID_SCORING_POLICY_VERSION",
    "Win5JudgementOutcome",
    "Win5NormalJudgementItem",
    "Win5NormalResultPlacement",
    "Win5NormalScoringPick",
    "Win5NormalSubmissionScore",
    "Win5Race",
    "Win5RaceEntry",
    "Win5RaceResult",
    "Win5Round",
    "Win5RoundSourceKind",
    "Win5RoundStatus",
    "Win5RoundType",
    "Win5SeasonStatus",
    "Win5Submission",
    "Win5SubmissionPick",
    "Win5SubmissionStatus",
    "Win5SubmissionTier",
    "Win5SpecialResultWinner",
    "Win5SpecialJudgementItem",
    "Win5SpecialScoringPick",
    "Win5SpecialSubmissionScore",
    "Win5DomainError",
    "Win5RaceInvariantError",
    "Win5ResultInvariantError",
    "Win5SubmissionInvariantError",
    "Win5Placement",
    "validate_accepted_submission_uniqueness_per_persona_round",
    "validate_normal_round_result_structure",
    "validate_normal_round_submission_structure",
    "validate_pick_race_membership",
    "validate_special_round_result_structure",
    "validate_special_round_submission_structure",
    "validate_submission_for_round",
    "validate_win5_round_open_readiness",
    "validate_win5_round_race_cardinality",
    "fingerprint_normal_result",
    "fingerprint_special_result",
    "fingerprint_special_void_state",
    "normal_tier_capacity",
    "score_normal_submission",
    "score_special_submission",
    "validate_normal_score_totals",
    "validate_special_score_totals",
]
