"""Current pre-release V2 canonical baseline.

Revision ID: 20260824_0001
Revises:
Create Date: 2026-08-24

This revision replaces the disposable 20260821_0001 -> 20260824_0002 chain.
No persistent V2 schema consumer depends on either superseded revision.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260824_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the current V2 canonical schema from an empty database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_guild_settings",
        sa.Column("guild_id", sa.String(length=32), nullable=False),
        sa.Column("win5_announcement_channel_id", sa.String(length=32), nullable=True),
        sa.Column("match_announcement_channel_id", sa.String(length=32), nullable=True),
        sa.Column("log_channel_id", sa.String(length=32), nullable=True),
        sa.Column("operator_role_id", sa.String(length=32), nullable=True),
        sa.Column("bot_manager_role_id", sa.String(length=32), nullable=True),
        sa.Column("default_timezone", sa.String(length=32), nullable=False),
        sa.Column("win5_announcements_enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("match_announcements_enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "match_odds_refresh_mode",
            sa.Enum("normal", "live", name="match_odds_refresh_mode"),
            server_default=sa.text("'normal'"),
            nullable=False,
        ),
        sa.Column("match_odds_refresh_next_at", sa.DateTime(), nullable=True),
        sa.Column("match_odds_refresh_sequence", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("match_odds_last_projection_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("guild_id", name=op.f("pk_bot_guild_settings")),
    )
    op.create_table(
        "discord_publications",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.String(length=32), nullable=False),
        sa.Column("destination_kind", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("target_channel_id", sa.String(length=32), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("payload_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "suppressed",
                "awaiting_channel",
                "ready",
                "pending",
                "sent",
                "failed",
                "delivery_unknown",
                name="publication_status",
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("discord_message_id", sa.String(length=32), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("failure_stage", sa.String(length=16), nullable=True),
        sa.Column("attempt_started_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discord_publications")),
        sa.UniqueConstraint(
            "guild_id",
            "destination_kind",
            "event_key",
            name=op.f("uq_discord_publications_guild_id_destination_kind_event_key"),
        ),
    )
    op.create_index(
        op.f("ix_discord_publications_status_attempt_started_at"),
        "discord_publications",
        ["status", "attempt_started_at"],
        unique=False,
    )
    op.create_table(
        "game_account_registration_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.String(length=32), nullable=False),
        sa.Column("requester_discord_user_id", sa.String(length=32), nullable=False),
        sa.Column("discord_display_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("game_region", sa.Enum("KR", "JP", name="game_region"), nullable=False),
        sa.Column("uma_pid", sa.String(length=32), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=False),
        sa.Column("affiliation", sa.String(length=100), nullable=True),
        sa.Column(
            "status", sa.Enum("pending", "approved", "cancelled", name="registration_request_status"), nullable=False
        ),
        sa.Column("active_marker", sa.Boolean(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "active_marker IS NULL OR active_marker = 1",
            name=op.f("ck_game_account_registration_requests_active_marker_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_account_registration_requests")),
        sa.UniqueConstraint(
            "guild_id",
            "requester_discord_user_id",
            "active_marker",
            name=op.f("uq_game_account_registration_requests_guild_id_requester_discord_user_id_active_marker"),
        ),
    )
    op.create_table(
        "operations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.String(length=32), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("actor_discord_user_id", sa.String(length=32), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_operations_idempotency_key")),
    )
    op.create_index(op.f("ix_operations_correlation_id"), "operations", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_operations_guild_id"), "operations", ["guild_id"], unique=False)
    op.create_table(
        "personas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("normal", "warning", "pending_approval", "expelled", "withdrawn", name="persona_status"),
            server_default=sa.text("'normal'"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personas")),
    )
    op.create_table(
        "stadiums",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.BigInteger(), nullable=False),
        sa.Column("name_jp", sa.String(length=100), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stadiums")),
        sa.UniqueConstraint("external_id", name=op.f("uq_stadiums_external_id")),
    )
    op.create_table(
        "umamusumes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.BigInteger(), nullable=False),
        sa.Column("name_jp", sa.String(length=100), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_umamusumes")),
        sa.UniqueConstraint("external_id", name=op.f("uq_umamusumes_external_id")),
    )
    op.create_table(
        "win5_seasons",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "active", "closed", "cancelled", name="win5_season_status"), nullable=False
        ),
        sa.Column("active_marker", sa.Boolean(), nullable=True),
        sa.Column("starts_at", sa.DateTime(), nullable=True),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "active_marker IS NULL OR active_marker = 1",
            name=op.f("ck_win5_seasons_active_marker_is_true_or_null"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_win5_seasons")),
        sa.UniqueConstraint("active_marker", name=op.f("uq_win5_seasons_active_marker")),
    )
    op.create_table(
        "bet_operations",
        sa.Column("operation_id", sa.BigInteger(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("bet_id", sa.BigInteger(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("before_data", sa.JSON(), nullable=True),
        sa.Column("after_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["operations.id"], name=op.f("fk_bet_operations_operation_id_operations")
        ),
        sa.PrimaryKeyConstraint("operation_id", name=op.f("pk_bet_operations")),
    )
    op.create_index(op.f("ix_bet_operations_bet_id"), "bet_operations", ["bet_id"], unique=False)
    op.create_index(op.f("ix_bet_operations_match_id"), "bet_operations", ["match_id"], unique=False)
    op.create_table(
        "circle_points",
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("balance", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["persona_id"], ["personas.id"], name=op.f("fk_circle_points_persona_id_personas")),
        sa.PrimaryKeyConstraint("persona_id", name=op.f("pk_circle_points")),
    )
    op.create_table(
        "discord_accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("discord_user_id", sa.String(length=32), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["persona_id"], ["personas.id"], name=op.f("fk_discord_accounts_persona_id_personas")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discord_accounts")),
        sa.UniqueConstraint("discord_user_id", name=op.f("uq_discord_accounts_discord_user_id")),
    )
    op.create_table(
        "game_accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("game_region", sa.Enum("KR", "JP", name="game_region"), nullable=False),
        sa.Column("uma_pid", sa.String(length=32), nullable=True),
        sa.Column("nickname", sa.String(length=100), nullable=False),
        sa.Column("affiliation", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["persona_id"], ["personas.id"], name=op.f("fk_game_accounts_persona_id_personas")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_accounts")),
        sa.UniqueConstraint("game_region", "uma_pid", name=op.f("uq_game_accounts_game_region_uma_pid")),
    )
    op.create_table(
        "identity_operations",
        sa.Column("operation_id", sa.BigInteger(), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=True),
        sa.Column("game_account_id", sa.BigInteger(), nullable=True),
        sa.Column("discord_user_id", sa.String(length=32), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("before_data", sa.JSON(), nullable=True),
        sa.Column("after_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["operations.id"], name=op.f("fk_identity_operations_operation_id_operations")
        ),
        sa.PrimaryKeyConstraint("operation_id", name=op.f("pk_identity_operations")),
    )
    op.create_table(
        "match_operations",
        sa.Column("operation_id", sa.BigInteger(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("before_data", sa.JSON(), nullable=True),
        sa.Column("after_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["operations.id"], name=op.f("fk_match_operations_operation_id_operations")
        ),
        sa.PrimaryKeyConstraint("operation_id", name=op.f("pk_match_operations")),
    )
    op.create_index(op.f("ix_match_operations_match_id"), "match_operations", ["match_id"], unique=False)
    op.create_table(
        "point_transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_point_transactions_operation_id_operations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"], ["personas.id"], name=op.f("fk_point_transactions_persona_id_personas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_point_transactions")),
    )
    op.create_index(op.f("ix_point_transactions_operation_id"), "point_transactions", ["operation_id"], unique=False)
    op.create_index(op.f("ix_point_transactions_persona_id"), "point_transactions", ["persona_id"], unique=False)
    op.create_table(
        "settings_operations",
        sa.Column("operation_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("before_data", sa.JSON(), nullable=True),
        sa.Column("after_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["operations.id"], name=op.f("fk_settings_operations_operation_id_operations")
        ),
        sa.PrimaryKeyConstraint("operation_id", name=op.f("pk_settings_operations")),
    )
    op.create_index(op.f("ix_settings_operations_guild_id"), "settings_operations", ["guild_id"], unique=False)
    op.create_table(
        "stadium_courses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("stadium_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.BigInteger(), nullable=False),
        sa.Column("surface", sa.Enum("turf", "dirt", name="match_surface"), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.Column("direction", sa.Enum("left", "right", "straight", name="match_direction"), nullable=False),
        sa.Column(
            "layout",
            sa.Enum("standard", "inner", "outer", "outer_to_inner", name="stadium_course_layout"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["stadium_id"], ["stadiums.id"], name=op.f("fk_stadium_courses_stadium_id_stadiums")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stadium_courses")),
        sa.UniqueConstraint("external_id", name=op.f("uq_stadium_courses_external_id")),
        sa.UniqueConstraint(
            "stadium_id",
            "surface",
            "distance",
            "direction",
            "layout",
            name=op.f("uq_stadium_courses_stadium_id_surface_distance_direction_layout"),
        ),
    )
    op.create_table(
        "umamusume_variants",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("umamusume_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.BigInteger(), nullable=False),
        sa.Column("name_jp", sa.String(length=100), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["umamusume_id"], ["umamusumes.id"], name=op.f("fk_umamusume_variants_umamusume_id_umamusumes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_umamusume_variants")),
        sa.UniqueConstraint("external_id", name=op.f("uq_umamusume_variants_external_id")),
        sa.UniqueConstraint("id", "umamusume_id", name=op.f("uq_umamusume_variants_id_umamusume_id")),
    )
    op.create_table(
        "win5_operations",
        sa.Column("operation_id", sa.BigInteger(), nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=True),
        sa.Column("round_id", sa.BigInteger(), nullable=True),
        sa.Column("submission_id", sa.BigInteger(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("before_data", sa.JSON(), nullable=True),
        sa.Column("after_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["operations.id"], name=op.f("fk_win5_operations_operation_id_operations")
        ),
        sa.PrimaryKeyConstraint("operation_id", name=op.f("pk_win5_operations")),
    )
    op.create_index(op.f("ix_win5_operations_round_id"), "win5_operations", ["round_id"], unique=False)
    op.create_index(op.f("ix_win5_operations_season_id"), "win5_operations", ["season_id"], unique=False)
    op.create_index(op.f("ix_win5_operations_submission_id"), "win5_operations", ["submission_id"], unique=False)
    op.create_table(
        "win5_rounds",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source_kind",
            sa.Enum("native_v2", "imported_v1", name="win5_round_source_kind"),
            server_default=sa.text("'native_v2'"),
            nullable=False,
        ),
        sa.Column("type", sa.Enum("normal", "special", name="win5_round_type"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("setup", "open", "closed", "scored", "cancelled", name="win5_round_status"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("opens_at", sa.DateTime(), nullable=True),
        sa.Column("closes_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["win5_seasons.id"], name=op.f("fk_win5_rounds_season_id_win5_seasons")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_win5_rounds")),
    )
    op.create_index(
        op.f("ix_win5_rounds_source_kind_status"),
        "win5_rounds",
        ["source_kind", "status"],
        unique=False,
    )
    op.create_table(
        "win5_scores",
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("season_score", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("top1_score", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["persona_id"], ["personas.id"], name=op.f("fk_win5_scores_persona_id_personas")),
        sa.ForeignKeyConstraint(["season_id"], ["win5_seasons.id"], name=op.f("fk_win5_scores_season_id_win5_seasons")),
        sa.PrimaryKeyConstraint("season_id", "persona_id", name=op.f("pk_win5_scores")),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source_kind",
            sa.Enum("native_v2", "imported_v1", name="match_source_kind"),
            server_default=sa.text("'native_v2'"),
            nullable=False,
        ),
        sa.Column("grade", sa.Enum("G1", "G2", "G3", "LISTED", "OP", name="match_grade"), nullable=False),
        sa.Column("stadium_course_id", sa.BigInteger(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "entry_confirmed",
                "betting_open",
                "betting_closed",
                "result_confirmed",
                "settled",
                "cancelled",
                "voided",
                name="match_status",
            ),
            nullable=False,
        ),
        sa.Column("terminal_reason", sa.String(length=255), nullable=True),
        sa.Column("finish_time_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stadium_course_id"], ["stadium_courses.id"], name=op.f("fk_matches_stadium_course_id_stadium_courses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
    )
    op.create_index(op.f("ix_matches_scheduled_at"), "matches", ["scheduled_at"], unique=False)
    op.create_index(op.f("ix_matches_source_kind_status"), "matches", ["source_kind", "status"], unique=False)
    op.create_index(op.f("ix_matches_status"), "matches", ["status"], unique=False)
    op.create_table(
        "rating_rule_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("source_identifier", sa.String(length=200), nullable=False),
        sa.Column("source_checksum", sa.String(length=64), nullable=False),
        sa.Column("source_sheet_name", sa.String(length=100), nullable=False),
        sa.Column("source_range", sa.String(length=64), nullable=False),
        sa.Column("rule_set_checksum", sa.String(length=64), nullable=False),
        sa.Column("rule_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rating_rule_versions")),
        sa.UniqueConstraint(
            "source_identifier",
            "source_checksum",
            "source_sheet_name",
            "source_range",
            name=op.f("uq_rating_rule_versions_source_identifier_source_checksum_source_sheet_name_source_range"),
        ),
        sa.UniqueConstraint("version_number", name=op.f("uq_rating_rule_versions_version_number")),
    )
    op.create_table(
        "rating_rules",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("rating_rule_version_id", sa.BigInteger(), nullable=False),
        sa.Column("grade", sa.String(length=8), nullable=False),
        sa.Column("participant_count", sa.Integer(), nullable=False),
        sa.Column("converted_rank", sa.Integer(), nullable=False),
        sa.Column("base_delta", sa.Numeric(precision=30, scale=18), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rating_rule_version_id"],
            ["rating_rule_versions.id"],
            name=op.f("fk_rating_rules_rating_rule_version_id_rating_rule_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rating_rules")),
        sa.UniqueConstraint(
            "rating_rule_version_id",
            "grade",
            "participant_count",
            "converted_rank",
            name=op.f("uq_rating_rules_rating_rule_version_id_grade_participant_count_converted_rank"),
        ),
    )
    op.create_index(
        op.f("ix_rating_rules_rating_rule_version_id"),
        "rating_rules",
        ["rating_rule_version_id"],
        unique=False,
    )
    op.create_table(
        "ratings",
        sa.Column("game_account_id", sa.BigInteger(), nullable=False),
        sa.Column("rating", sa.Numeric(precision=30, scale=18), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_account_id"], ["game_accounts.id"], name=op.f("fk_ratings_game_account_id_game_accounts")
        ),
        sa.PrimaryKeyConstraint("game_account_id", name=op.f("pk_ratings")),
    )
    op.create_table(
        "win5_races",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("round_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("void_reason", sa.String(length=255), nullable=True),
        sa.Column("voided_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(void_reason IS NULL AND voided_at IS NULL) OR (void_reason IS NOT NULL AND voided_at IS NOT NULL)",
            name=op.f("ck_win5_races_void_fact_complete"),
        ),
        sa.ForeignKeyConstraint(["round_id"], ["win5_rounds.id"], name=op.f("fk_win5_races_round_id_win5_rounds")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_win5_races")),
    )
    op.create_table(
        "win5_submissions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("round_id", sa.BigInteger(), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column(
            "tier", sa.Enum("TOP1", "TOP3", "TOP5", "SPECIAL_WINNER", name="win5_submission_tier"), nullable=False
        ),
        sa.Column("status", sa.Enum("accepted", "cancelled", name="win5_submission_status"), nullable=False),
        sa.Column("active_marker", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "active_marker IS NULL OR active_marker = 1", name=op.f("ck_win5_submissions_active_marker_is_true_or_null")
        ),
        sa.ForeignKeyConstraint(["persona_id"], ["personas.id"], name=op.f("fk_win5_submissions_persona_id_personas")),
        sa.ForeignKeyConstraint(
            ["round_id"], ["win5_rounds.id"], name=op.f("fk_win5_submissions_round_id_win5_rounds")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_win5_submissions")),
        sa.UniqueConstraint(
            "round_id",
            "persona_id",
            "active_marker",
            name=op.f("uq_win5_submissions_round_id_persona_id_active_marker"),
        ),
    )
    op.create_table(
        "bets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.Enum("win", "quinella", "trio", name="bet_type"), nullable=False),
        sa.Column("selections", sa.JSON(), nullable=False),
        sa.Column("selection_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Enum("active", "settled", "cancelled", name="bet_status"), nullable=False),
        sa.Column("active_marker", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "active_marker IS NULL OR active_marker = 1", name=op.f("ck_bets_active_marker_is_true_or_null")
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], name=op.f("fk_bets_match_id_matches")),
        sa.ForeignKeyConstraint(["persona_id"], ["personas.id"], name=op.f("fk_bets_persona_id_personas")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bets")),
        sa.UniqueConstraint(
            "match_id",
            "persona_id",
            "type",
            "selection_fingerprint",
            "active_marker",
            name=op.f("uq_bets_match_id_persona_id_type_selection_fingerprint_active_marker"),
        ),
    )
    op.create_index(op.f("ix_bets_match_id"), "bets", ["match_id"], unique=False)
    op.create_index(op.f("ix_bets_persona_id"), "bets", ["persona_id"], unique=False)
    op.create_table(
        "match_conditions",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("season", sa.Enum("spring", "summer", "autumn", "winter", name="match_season"), nullable=False),
        sa.Column("weather", sa.Enum("sunny", "cloudy", "rain", "snow", name="match_weather"), nullable=False),
        sa.Column("time_of_day", sa.Enum("day", "night", name="match_time_of_day"), nullable=False),
        sa.Column(
            "track_condition", sa.Enum("firm", "good", "soft", "heavy", name="match_track_condition"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], name=op.f("fk_match_conditions_match_id_matches")),
        sa.PrimaryKeyConstraint("match_id", name=op.f("pk_match_conditions")),
    )
    op.create_table(
        "match_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("game_account_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_at_event_persona_id", sa.String(length=36), nullable=False),
        sa.Column("affiliation_at_event", sa.String(length=100), nullable=True),
        sa.Column("umamusume_id", sa.BigInteger(), nullable=False),
        sa.Column("umamusume_variant_id", sa.BigInteger(), nullable=True),
        sa.Column("entry_number", sa.Integer(), nullable=False),
        sa.Column("running_style", sa.String(length=32), nullable=True),
        sa.Column("training_grade", sa.String(length=16), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("popularity_rank", sa.Integer(), nullable=True),
        sa.Column("margin", sa.String(length=16), nullable=True),
        sa.Column(
            "rating_disposition",
            sa.Enum("rated", "excluded", "not_applicable", name="match_rating_disposition"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_account_id"], ["game_accounts.id"], name=op.f("fk_match_entries_game_account_id_game_accounts")
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], name=op.f("fk_match_entries_match_id_matches")),
        sa.ForeignKeyConstraint(
            ["owner_at_event_persona_id"],
            ["personas.id"],
            name=op.f("fk_match_entries_owner_at_event_persona_id_personas"),
        ),
        sa.ForeignKeyConstraint(
            ["umamusume_id"], ["umamusumes.id"], name=op.f("fk_match_entries_umamusume_id_umamusumes")
        ),
        sa.ForeignKeyConstraint(
            ["umamusume_variant_id", "umamusume_id"],
            ["umamusume_variants.id", "umamusume_variants.umamusume_id"],
            name=op.f("fk_match_entries_umamusume_variant_id_umamusume_id_umamusume_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_entries")),
        sa.UniqueConstraint("match_id", "entry_number", name=op.f("uq_match_entries_match_id_entry_number")),
        sa.UniqueConstraint("match_id", "popularity_rank", name=op.f("uq_match_entries_match_id_popularity_rank")),
        sa.UniqueConstraint("match_id", "rank", name=op.f("uq_match_entries_match_id_rank")),
    )
    op.create_index(op.f("ix_match_entries_match_id_game_account_id"), "match_entries", ["match_id", "game_account_id"])
    op.create_table(
        "match_result_submissions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.Enum("manual", "ocr", name="match_result_source_kind"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "confirmed", "rejected", "superseded", name="match_result_submission_status"),
            nullable=False,
        ),
        sa.Column("pending_marker", sa.Boolean(), nullable=True),
        sa.Column("confirmed_marker", sa.Boolean(), nullable=True),
        sa.Column("candidate_json", sa.JSON(), nullable=False),
        sa.Column("submitted_operation_id", sa.BigInteger(), nullable=True),
        sa.Column("rejected_operation_id", sa.BigInteger(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=255), nullable=True),
        sa.Column("confirmed_operation_id", sa.BigInteger(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "confirmed_marker IS NULL OR confirmed_marker = 1",
            name=op.f("ck_match_result_submissions_confirmed_marker_is_true_or_null"),
        ),
        sa.CheckConstraint(
            "pending_marker IS NULL OR pending_marker = 1",
            name=op.f("ck_match_result_submissions_pending_marker_is_true_or_null"),
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_operation_id"],
            ["operations.id"],
            name=op.f("fk_match_result_submissions_confirmed_operation_id_operations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_result_submissions_match_id_matches"),
        ),
        sa.ForeignKeyConstraint(
            ["rejected_operation_id"],
            ["operations.id"],
            name=op.f("fk_match_result_submissions_rejected_operation_id_operations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_operation_id"],
            ["operations.id"],
            name=op.f("fk_match_result_submissions_submitted_operation_id_operations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_result_submissions")),
        sa.UniqueConstraint(
            "confirmed_operation_id",
            name=op.f("uq_match_result_submissions_confirmed_operation_id"),
        ),
        sa.UniqueConstraint(
            "match_id",
            "confirmed_marker",
            name=op.f("uq_match_result_submissions_match_id_confirmed_marker"),
        ),
        sa.UniqueConstraint(
            "match_id",
            "pending_marker",
            name=op.f("uq_match_result_submissions_match_id_pending_marker"),
        ),
        sa.UniqueConstraint(
            "match_id",
            "revision_number",
            name=op.f("uq_match_result_submissions_match_id_revision_number"),
        ),
        sa.UniqueConstraint(
            "rejected_operation_id",
            name=op.f("uq_match_result_submissions_rejected_operation_id"),
        ),
        sa.UniqueConstraint(
            "submitted_operation_id",
            name=op.f("uq_match_result_submissions_submitted_operation_id"),
        ),
    )
    op.create_index(
        op.f("ix_match_result_submissions_match_id"),
        "match_result_submissions",
        ["match_id"],
        unique=False,
    )
    op.create_table(
        "win5_race_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("race_id", sa.BigInteger(), nullable=False),
        sa.Column("gate_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["race_id"], ["win5_races.id"], name=op.f("fk_win5_race_entries_race_id_win5_races")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_win5_race_entries")),
        sa.UniqueConstraint("id", "race_id", name=op.f("uq_win5_race_entries_id_race_id")),
        sa.UniqueConstraint("race_id", "gate_number", name=op.f("uq_win5_race_entries_race_id_gate_number")),
    )
    op.create_table(
        "rating_transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("operation_id", sa.BigInteger(), nullable=True),
        sa.Column("rating_rule_version_id", sa.BigInteger(), nullable=False),
        sa.Column("match_entry_id", sa.BigInteger(), nullable=False),
        sa.Column("rating_before", sa.Numeric(precision=30, scale=18), nullable=False),
        sa.Column("amount", sa.Numeric(precision=30, scale=18), nullable=False),
        sa.Column("rating_after", sa.Numeric(precision=30, scale=18), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "rating_after = rating_before + amount", name=op.f("ck_rating_transactions_balanced_rating_delta")
        ),
        sa.ForeignKeyConstraint(
            ["match_entry_id"], ["match_entries.id"], name=op.f("fk_rating_transactions_match_entry_id_match_entries")
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_rating_transactions_operation_id_operations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rating_rule_version_id"],
            ["rating_rule_versions.id"],
            name=op.f("fk_rating_transactions_rating_rule_version_id_rating_rule_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rating_transactions")),
    )
    op.create_index(
        op.f("ix_rating_transactions_match_entry_id"), "rating_transactions", ["match_entry_id"], unique=False
    )
    op.create_index(op.f("ix_rating_transactions_operation_id"), "rating_transactions", ["operation_id"], unique=False)
    op.create_index(
        op.f("ix_rating_transactions_rating_rule_version_id"),
        "rating_transactions",
        ["rating_rule_version_id"],
        unique=False,
    )
    op.create_table(
        "win5_results",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("race_id", sa.BigInteger(), nullable=False),
        sa.Column("race_entry_id", sa.BigInteger(), nullable=True),
        sa.Column("gate_number", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["race_entry_id", "race_id"],
            ["win5_race_entries.id", "win5_race_entries.race_id"],
            name=op.f("fk_win5_results_race_entry_id_race_id_win5_race_entries"),
        ),
        sa.ForeignKeyConstraint(["race_id"], ["win5_races.id"], name=op.f("fk_win5_results_race_id_win5_races")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_win5_results")),
        sa.UniqueConstraint("race_id", "position", name=op.f("uq_win5_results_race_id_position")),
        sa.UniqueConstraint("race_id", "race_entry_id", name=op.f("uq_win5_results_race_id_race_entry_id")),
    )
    op.create_table(
        "win5_submission_picks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("submission_id", sa.BigInteger(), nullable=False),
        sa.Column("race_id", sa.BigInteger(), nullable=False),
        sa.Column("race_entry_id", sa.BigInteger(), nullable=True),
        sa.Column("gate_number", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["race_entry_id", "race_id"],
            ["win5_race_entries.id", "win5_race_entries.race_id"],
            name=op.f("fk_win5_submission_picks_race_entry_id_race_id_win5_race_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["race_id"], ["win5_races.id"], name=op.f("fk_win5_submission_picks_race_id_win5_races")
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["win5_submissions.id"],
            name=op.f("fk_win5_submission_picks_submission_id_win5_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_win5_submission_picks")),
        sa.UniqueConstraint(
            "submission_id", "race_id", "position", name=op.f("uq_win5_submission_picks_submission_id_race_id_position")
        ),
        sa.UniqueConstraint(
            "submission_id",
            "race_id",
            "race_entry_id",
            name=op.f("uq_win5_submission_picks_submission_id_race_id_race_entry_id"),
        ),
    )
    op.create_table(
        "win5_score_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("operation_id", sa.BigInteger(), nullable=True),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("round_id", sa.BigInteger(), nullable=False),
        sa.Column("race_id", sa.BigInteger(), nullable=True),
        sa.Column("submission_id", sa.BigInteger(), nullable=False),
        sa.Column("submission_version", sa.Integer(), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column(
            "tier",
            sa.Enum("TOP1", "TOP3", "TOP5", "SPECIAL_WINNER", name="win5_submission_tier"),
            nullable=False,
        ),
        sa.Column("result_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("scoring_policy_version", sa.String(length=64), nullable=False),
        sa.Column("reward_policy_version", sa.String(length=64), nullable=False),
        sa.Column("exact_count", sa.Integer(), nullable=False),
        sa.Column("wrong_position_count", sa.Integer(), nullable=False),
        sa.Column("off_board_count", sa.Integer(), nullable=False),
        sa.Column("missing_count", sa.Integer(), nullable=False),
        sa.Column("season_score_delta", sa.Integer(), nullable=False),
        sa.Column("top1_score_delta", sa.Integer(), nullable=False),
        sa.Column("circle_point_reward", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_win5_score_events_operation_id_operations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["persona_id"], ["personas.id"], name=op.f("fk_win5_score_events_persona_id_personas")),
        sa.ForeignKeyConstraint(["race_id"], ["win5_races.id"], name=op.f("fk_win5_score_events_race_id_win5_races")),
        sa.ForeignKeyConstraint(
            ["round_id"], ["win5_rounds.id"], name=op.f("fk_win5_score_events_round_id_win5_rounds")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["win5_seasons.id"], name=op.f("fk_win5_score_events_season_id_win5_seasons")
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["win5_submissions.id"],
            name=op.f("fk_win5_score_events_submission_id_win5_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_win5_score_events")),
        sa.UniqueConstraint("round_id", "persona_id", name=op.f("uq_win5_score_events_round_id_persona_id")),
        sa.UniqueConstraint("submission_id", name=op.f("uq_win5_score_events_submission_id")),
    )
    op.create_index(op.f("ix_win5_score_events_operation_id"), "win5_score_events", ["operation_id"], unique=False)
    op.create_index(op.f("ix_win5_score_events_persona_id"), "win5_score_events", ["persona_id"], unique=False)
    op.create_index(op.f("ix_win5_score_events_round_id"), "win5_score_events", ["round_id"], unique=False)
    op.create_index(op.f("ix_win5_score_events_season_id"), "win5_score_events", ["season_id"], unique=False)
    op.create_table(
        "win5_score_event_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("score_event_id", sa.BigInteger(), nullable=False),
        sa.Column("race_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("submission_pick_id", sa.BigInteger(), nullable=True),
        sa.Column("matched_result_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("exact", "wrong_position", "off_board", "missing", "void", name="win5_judgement_outcome"),
            nullable=False,
        ),
        sa.Column("season_score_delta", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_result_id"],
            ["win5_results.id"],
            name=op.f("fk_win5_score_event_items_matched_result_id_win5_results"),
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["win5_races.id"],
            name=op.f("fk_win5_score_event_items_race_id_win5_races"),
        ),
        sa.ForeignKeyConstraint(
            ["score_event_id"],
            ["win5_score_events.id"],
            name=op.f("fk_win5_score_event_items_score_event_id_win5_score_events"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_pick_id"],
            ["win5_submission_picks.id"],
            name=op.f("fk_win5_score_event_items_submission_pick_id_win5_submission_picks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_win5_score_event_items")),
        sa.UniqueConstraint(
            "score_event_id",
            "race_id",
            "position",
            name=op.f("uq_win5_score_event_items_score_event_id_race_id_position"),
        ),
        sa.UniqueConstraint("submission_pick_id", name=op.f("uq_win5_score_event_items_submission_pick_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the disposable V2 canonical schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("win5_score_event_items")
    op.drop_index(op.f("ix_win5_score_events_season_id"), table_name="win5_score_events")
    op.drop_index(op.f("ix_win5_score_events_round_id"), table_name="win5_score_events")
    op.drop_index(op.f("ix_win5_score_events_persona_id"), table_name="win5_score_events")
    op.drop_index(op.f("ix_win5_score_events_operation_id"), table_name="win5_score_events")
    op.drop_table("win5_score_events")
    op.drop_table("win5_submission_picks")
    op.drop_table("win5_results")
    op.drop_index(op.f("ix_rating_transactions_rating_rule_version_id"), table_name="rating_transactions")
    op.drop_index(op.f("ix_rating_transactions_operation_id"), table_name="rating_transactions")
    op.drop_index(op.f("ix_rating_transactions_match_entry_id"), table_name="rating_transactions")
    op.drop_table("rating_transactions")
    op.drop_table("win5_race_entries")
    op.drop_index(op.f("ix_match_result_submissions_match_id"), table_name="match_result_submissions")
    op.drop_table("match_result_submissions")
    op.drop_table("match_entries")
    op.drop_table("match_conditions")
    op.drop_index(op.f("ix_bets_persona_id"), table_name="bets")
    op.drop_index(op.f("ix_bets_match_id"), table_name="bets")
    op.drop_table("bets")
    op.drop_table("win5_submissions")
    op.drop_table("win5_races")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_rating_rules_rating_rule_version_id"), table_name="rating_rules")
    op.drop_table("rating_rules")
    op.drop_table("rating_rule_versions")
    op.drop_index(op.f("ix_matches_status"), table_name="matches")
    op.drop_index(op.f("ix_matches_source_kind_status"), table_name="matches")
    op.drop_index(op.f("ix_matches_scheduled_at"), table_name="matches")
    op.drop_table("matches")
    op.drop_table("win5_scores")
    op.drop_index(op.f("ix_win5_rounds_source_kind_status"), table_name="win5_rounds")
    op.drop_table("win5_rounds")
    op.drop_index(op.f("ix_win5_operations_submission_id"), table_name="win5_operations")
    op.drop_index(op.f("ix_win5_operations_season_id"), table_name="win5_operations")
    op.drop_index(op.f("ix_win5_operations_round_id"), table_name="win5_operations")
    op.drop_table("win5_operations")
    op.drop_table("umamusume_variants")
    op.drop_table("stadium_courses")
    op.drop_index(op.f("ix_settings_operations_guild_id"), table_name="settings_operations")
    op.drop_table("settings_operations")
    op.drop_index(op.f("ix_point_transactions_persona_id"), table_name="point_transactions")
    op.drop_index(op.f("ix_point_transactions_operation_id"), table_name="point_transactions")
    op.drop_table("point_transactions")
    op.drop_index(op.f("ix_match_operations_match_id"), table_name="match_operations")
    op.drop_table("match_operations")
    op.drop_table("identity_operations")
    op.drop_table("game_accounts")
    op.drop_table("discord_accounts")
    op.drop_table("circle_points")
    op.drop_index(op.f("ix_bet_operations_match_id"), table_name="bet_operations")
    op.drop_index(op.f("ix_bet_operations_bet_id"), table_name="bet_operations")
    op.drop_table("bet_operations")
    op.drop_table("win5_seasons")
    op.drop_table("umamusumes")
    op.drop_table("stadiums")
    op.drop_table("personas")
    op.drop_index(op.f("ix_operations_guild_id"), table_name="operations")
    op.drop_index(op.f("ix_operations_correlation_id"), table_name="operations")
    op.drop_table("operations")
    op.drop_table("game_account_registration_requests")
    op.drop_index(op.f("ix_discord_publications_status_attempt_started_at"), table_name="discord_publications")
    op.drop_table("discord_publications")
    op.drop_table("bot_guild_settings")
    # ### end Alembic commands ###
