"""Betting domain package for pure calculation kernel."""

from .calculator import (
    APPLIED_ODDS_QUANTUM,
    BET_STAKE_CAP_PERCENT,
    BET_STAKE_UNIT,
    PROVISIONAL_ODDS_QUANTUM,
    WEIGHTED_ODDS_RULE_VERSION,
    BetPoolStake,
    BetStatus,
    BetType,
    ProvisionalSelectionOdds,
    ZeroPoolMarketOdds,
    calculate_bet_stake_cap,
    calculate_payout,
    calculate_provisional_odds,
    calculate_refund,
    calculate_zero_pool_market_odds,
    canonicalize_selections,
    quantize_applied_odds,
    quantize_provisional_odds,
    validate_new_bet_stake,
)
from .errors import BettingDomainError, BettingOddsError, BettingSelectionError, BettingStakeError

__all__ = [
    "APPLIED_ODDS_QUANTUM",
    "BET_STAKE_CAP_PERCENT",
    "BET_STAKE_UNIT",
    "PROVISIONAL_ODDS_QUANTUM",
    "WEIGHTED_ODDS_RULE_VERSION",
    "BetPoolStake",
    "BetStatus",
    "BetType",
    "BettingDomainError",
    "BettingOddsError",
    "BettingSelectionError",
    "BettingStakeError",
    "ProvisionalSelectionOdds",
    "ZeroPoolMarketOdds",
    "calculate_bet_stake_cap",
    "calculate_payout",
    "calculate_provisional_odds",
    "calculate_refund",
    "calculate_zero_pool_market_odds",
    "canonicalize_selections",
    "quantize_applied_odds",
    "quantize_provisional_odds",
    "validate_new_bet_stake",
]
